import "./globals.css";
import Navigation from '@/components/Navigation'
import '../public/bootstrap.min.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navigation />
      <Navbar />
        {children}
      
      </body>
      
    </html>
  )
}
